config/routes.rb
Rails.application.routes.draw do
  # Define routes for emotions and affirmations controllers
  resources :emotions
  resources :affirmations
  
  # Set the root path of your application
  root 'home#index'

  delete '/affirmations/:id', to: 'affirmations#destroy'
  delete '/emotions/:id', to: 'emotions#destroy'
end

app/models/affirmation.rb
class Affirmation < ApplicationRecord
    has_many :emotion_affirmations, dependent: :destroy
    has_many :emotions, through: :emotion_affirmations
    belongs_to :emotion
    validates :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/emotion.rb
class Emotion < ApplicationRecord
    has_many :emotion_affirmations
    has_many :affirmations, through: :emotion_affirmations
    validates :name, presence: true, uniqueness: true
end

app/controllers/affirmations_controller.rb
class AffirmationsController < ApplicationController
  def new
    @affirmation = Affirmation.new
  end

  def index
    @affirmations = Affirmation.all
  end

  def show
    @affirmation = Affirmation.find_by(id: params[:id])
    if @affirmation.nil?
      flash[:alert] = "Affirmation not found"
      redirect_to affirmation_path
    end
  end
  
  def create
    @affirmation = Affirmation.new(affirmation_params)

    if @affirmation.save
      redirect_to @affirmation, notice: 'Affirmation was successfully created.'
    else
      render :new
    end
  end

  def edit
    @affirmation = Affirmation.find(params[:id])
  end

  def update
    @affirmation = Affirmation.find(params[:id])
    if @affirmation.update(affirmation_params)
      redirect_to @affirmation, notice: 'Affirmation was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @affirmation = Affirmation.find(params[:id])
    @affirmation.destroy
    redirect_to affirmation_path notice: 'Content was successfully destroyed.'
  end

  private

  def set_affirmation
    @affirmation = Affirmation.find(params[:id])
  end

  def affirmation_params
    params.require(:affirmation).permit(:content, :emotion_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
    
  def index
    @emotions = Emotion.all
  end

  def show
    @emotion = Emotion.find_by(id: params[:id])
    if @emotion.nil?
      flash[:alert] = "Emotion not found"
      redirect_to emotions_path
    end
  end

  def new
    @emotion = Emotion.new
  end

  def create
    @emotion = Emotion.new(emotion_params)

    if @emotion.save
      redirect_to @emotion, notice: 'Emotion was successfully created.'
    else
      render :new
    end
  end

  def edit
    @emotion = Emotion.find_by(id:params[:id])
  end

  def update
    @emotion = Emotion.find(params[:id])
    if @emotion.update(emotion_params)
      redirect_to @emotion, notice: 'Emotion was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @emotion = Emotion.find(params[:id])
    @emotion.destroy
    redirect_to emotions_url, notice: 'Emotion was successfully destroyed.'
  end
  
  private

  def set_emotion
    @emotion = Emotion.find(params[:id])
  end

  def emotion_params
    params.require(:emotion).permit(:name, :intensity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
  end
  

app/helpers/affirmations_helper.rb
module AffirmationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/views/affirmations/_form.html.erb
<%= form_with(model: affirmation, local: true) do |form| %>
  <% if affirmation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(affirmation.errors.count, "error") %> prohibited this affirmation from being saved:</h2>

      <ul>
      <% affirmation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :emotion_id %>
    <%= form.collection_select :emotion_id, Emotion.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/affirmations/destroy.html.erb
<%= link_to 'Edit', edit_affirmation_path(affirmation)) %> |
<%= link_to 'Back', affirmations_path %>

<%= form_with(model: @affirmationn\, method: :delete, local: true) do |form| %>
  <%= form.submit 'Destroy', data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/affirmations/edit.html.erb
<h1>Edit Affirmation</h1>

<%= render 'form', affirmation: @affirmation %>

<%= link_to 'Show', @affirmation %> |
<%= link_to 'Back', affirmations_path %>

app/views/affirmations/index.html.erb
<h1>Affirmations</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Emotion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <% @affirmations.each do |affirmation| %>
        <td><%= affirmation.content %></td>
      
        <td><%= link_to 'Show', affirmation %></td>
        <td><%= link_to 'Edit', edit_affirmation_path(affirmation) %></td>
       
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Affirmation', new_affirmation_path %>

app/views/affirmations/new.html.erb
<h1>New Affirmation</h1>
<%= render "form", affirmation: @affirmation %>
<div>
<%= link_to "Back to affirmations", affirmations_path %>
</div> 

app/views/affirmations/show.html.erb
<h1>Affirmation</h1>
<p><strong>Content:</strong> <%= @affirmation.content %></p>
<p><strong>Emotion:</strong> <%= @affirmation.emotion.name %></p>

<%= link_to 'Edit', edit_affirmation_path(@affirmation) %> |
<%= link_to 'Back', affirmations_path %>
<%= link_to 'Delete', @Affirmations, method: :delete %>

app/views/emotions/_form.html.erb
<%= form_with(model: emotion, local: true) do |form| %>
  <% if emotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emotion.errors.count, "error") %> prohibited this emotion from being saved:</h2>

      <ul>
        <% emotion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :intensity %>
    <%= form.text_area :intensity, class: "form-control", rows: 3 %>
  </div>

  <div class="field">
    <%= form.label :emotions %>
    <%= form.text_area :emotions, class: "form-control", rows: 3 %>
  </div>
      
  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/emotions/destroy.html.erb
<%= link_to 'Edit', edit_emotion_path(@emotion) %> |
<%= link_to 'Back', emotions_path %>

<%= form_with(model: @emotion, method: :delete, local: true) do |form| %>
  <%= form.submit 'Destroy', data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/emotions/edit.html.erb
<h1>Edit Emotion</h1>

<%= render 'form', emotion: @emotion %>

<%= link_to 'Show', @emotion %> |
<%= link_to 'Back', emotions_path %>

app/views/emotions/index.html.erb
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
  Emotions
  </button>

<table>
  <thead>
    <tr>
      <th>Intensity</th>
      <th> Emotions </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @emotions.each do |emotion| %>
      <tr>
      <td><%= emotion.intensity %></td>
        <td><%= emotion.name %></td>
        <td><%= link_to 'Show', emotion %></td>
        <td><%= link_to 'Edit', edit_emotion_path(emotion) %></td>
        <td><%= link_to 'Delete', emotion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
  
<%= link_to 'New Emotion', new_emotion_path %>

app/views/emotions/new.html.erb
<h1>New Emotion</h1>
<%= render "form", emotion: @emotion %>

<div>
<%= link_to "Back to emotions", emotions_path %>
</div>

app/views/emotions/show.html.erb
<h1><%= @emotion.name %></h1>
<p><strong>Intensity:</strong> <%= @emotion.intensity %></p>

<%= link_to 'Edit', edit_emotion_path(@emotion) %> |
<%= link_to 'Back', emotions_path %>
<%= button_to "Destroy this emotion", @emotionn, method: :delete %>

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<div class="container">
  <div class="row">
      <h1>Welcome to the 
      Affirmation Diary!</h1>
      <div class="col-md-6 offset-md-3">
      <h2><i> This app allows you to log
       your emotions and mood and add your affirmation to lift your mood </i> </h2>

      <p> Choose an option below:</p>
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Log your Diary here:
        </button>
    </div>
  </div>
        <a href="<%= affirmations_path %>" class="btn btn-primary btn-lg mr-3">Affirmations</a>
        <a href="<%= emotions_path %>" class="btn btn-secondary btn-lg">Emotions</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Affirmations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'custom', media: 'all' %>
    <%= stylesheet_link_tag 'application', 'custom', media: 'all' %>
    
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Affirmation Generator', root_path, class: 'navbar-brand' %>
    </button>
    <div class="dropdown-menu" aria-labelledby="customerDropdown">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Emotions', emotions_path, class: 'nav-link' %>
        </li>
      </ul>
        <li class="nav-item">
        <div class="dropdown-menu" aria-labelledby="customerDropdown">
          <%= link_to 'Affirmations', affirmations_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>